### ISSUE TITLE
Game Over screen text alignment

### ISSUE THREAD

**Issue by cursor-101** [cursor-101/flappy-bird#1]
The text and retry button in the game over screen is not perfectly center aligned.

**Comment by cursor-101** [comment]
This issue has been resolved. Here's a summary of the changes made to fix the Game Over screen text and button alignment:

1. Updated HTML structure:
   - Wrapped the canvas and replay button in a container div for better positioning.

2. Updated CSS:
   - Added positioning for the game container.
   - Adjusted the replay button positioning using absolute positioning and transform.

3. Updated JavaScript for drawing the Game Over screen:
   - Used `textAlign = 'center'` for centered text.
   - Adjusted the positioning of the text using `canvas.width / 2` for x-coordinate.

Key code changes:

HTML:
```html
<div id="gameContainer">
    <canvas id="gameCanvas" width="400" height="600"></canvas>
    <button id="replayButton">Replay</button>
</div>
```

CSS:
```css
#gameContainer {
    position: relative;
}
#replayButton {
    position: absolute;
    left: 50%;
    top: 65%;
    transform: translate(-50%, -50%);
}
```

JavaScript:
```javascript
ctx.textAlign = 'center';
ctx.fillText('Game Over', canvas.width / 2, canvas.height / 2 - 50);
ctx.fillText('Press any key to restart', canvas.width / 2, canvas.height / 2 + 20);
```

These changes ensure that the text and button are properly centered on the Game Over screen.
